### ISSUE TITLE
Error when using template

### ISSUE THREAD

**Issue by Sophon96** [derail-valley-modding/template-umm#2]
When I try to create a repository from this template, GitHub errors a very ambiguous message: 
![image](https://github.com/derail-valley-modding/template-umm/assets/71684640/63952bd5-6fa0-4eb0-8a10-875eac853d17)

**Comment by Insprill** [comment]
Have you tried deleting the repository and trying again?

**Comment by Sophon96** [comment]
Yep.

**Comment by Sophon96** [comment]
Completely unreproducible now. :)
